name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libboost1.65-all-dev cmake make g++-8 freeglut3-dev && git submodule update --init --recursive
    - name: make
      run: mkdir build && cd build && cmake .. && make -j4
    - name: tests
      run: cd build/tests && ctest -l all
