name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libboost1.71-all-dev cmake make g++-9 freeglut3-dev
    - name: make
      run: mkdir build && cd build && cmake .. && make -j4
    - name: tests
      run: ./build/tests/engine_tests -l all
